# VisualAbility 플러그인 설정 파일입니다.
# 각 속성을 원하는 게임에 따라 세팅하세요.
# true와 false 철자 주의할것. 띄어쓰기도 틀려선 안됨.

시작후 초반 무적: true
초반 무적 시간(분 단위): 5
일부 능력 금지 시간(분 단위, 0은 사용 안함): 15
기본 무장 제공: true
S랭크 능력 사용: false
시작시 리스폰으로 이동: true
사망시 자동으로 킥: true
사망시 자동으로 밴(킥이 활성화 되어야 가능): false
몬스터의 공격력 반감: true
난이도 자동으로 Easy로 설정: true
만렙 서바이벌 모드: false
배고픔 무한 모드(관련 능력은 알아서 상향됨): false
죽을 경우 죽인 사람을 보여줌: true
일정시간마다 좌표 표시: true
동물 비활성화: false
퀵 스타트 모드: false
시작시 능력 추첨 안함: false
시작시 인벤토리 초기화 안함: false
시작후 팁 출력함: true
서버 오토 세이브: false
인벤토리 세이브: false
능력 중첩 가능: false
내구도 무한: false
데스노트 사용 안함: false
미러링 사용 안함: false