name: VisualAbility
main: Xeon.VisualAbility.VisualAbility
version: 1.9
api-version: 1.16
commands:
  va:
    description: This is a demo command.
    usage: /<command>
  bjstart:
    description: This is a demo command.
    usage: /<command>
